from . import hr_employee
from . import solidali_paghe_ra
from . import solidali_paghe_mav
from . import solidali_paghe_cud
from . import solidali_paghe_mav_periodo
from . import solidali_paghe_dettaglio
from . import solidali_paghe_settimane
from . import solidali_paghe
from . import sale_subscription
from . import solidali_presenze
from . import calendar_event
from . import account_move
from . import hr_contract
from . import hr_version
from . import hr_work_entry
from . import hr_work_entry_type
from . import sub_servizio_line
from . import sale_order_line
from . import resource_calendar_attendance
from . import solidali_titolo_studio
from . import solidali_lingua_conosciuta
from . import solidali_tipo_permesso
from . import solidali_motivo_permesso
from . import solidali_mezzo_locomozione
from . import solidali_rapporto_lavorativo
from . import solidali_figura_professionale
from . import solidali_tipo_ccnl
from . import solidali_regione_italiana
from . import solidali_corso_professionale
from . import res_partner
from . import res_company
